config/routes.rb
Biotriz::Application.routes.draw do
  resources :entity_actions

  resources :environment_parameters

  resources :entity_functions

  resources :entities

  resources :principles

  resources :parameters

  resources :complexities

  match 'user/edit' => 'users#edit', :as => :edit_current_user
  root :to => 'homes#index'

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users, except: :new # new users are not allowed for now

  resources :environments

  resources :sizes

end

app/controllers/entity_actions_controller.rb
class EntityActionsController < ApplicationController
  before_filter :login_required

  def index
    @entity_actions = EntityAction.paginate page: params[:page]
  end

  def show
    @entity_action = EntityAction.find(params[:id])
  end

  def new
    @entity_action = EntityAction.new
  end

  def create
    @entity_action = EntityAction.new(params[:entity_action])
    if @entity_action.save
      redirect_to @entity_action, :notice => "Successfully created action."
    else
      render :action => 'new'
    end
  end

  def edit
    @entity_action = EntityAction.find(params[:id])
  end

  def update
    @entity_action = EntityAction.find(params[:id])
    if @entity_action.update_attributes(params[:entity_action])
      redirect_to @entity_action, :notice  => "Successfully updated action."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @entity_action = EntityAction.find(params[:id])
    @entity_action.destroy
    redirect_to entity_actions_url, :notice => "Successfully destroyed action."
  end
end

app/helpers/entity_actions_helper.rb
module EntityActionsHelper
end

app/views/entity_actions/_form.html.erb
<div class="row">
  <div class="span6 offset3">

    <%= form_for @entity_action do |f| %>
      <%= display_error_messages_for f %>

      <p>
        <%= f.label :parent_id %>
        <%= hierarchical_select :entity_action, :parent_id, EntityAction,
            { include_blank: true }, { size: "10" } %>
      </p>
      <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </p>
      <p>
        <%= f.label :description %>
        <%= f.text_area :description %>
      </p>
      <p><%= f.submit "New Action", class: "btn btn-large btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/entity_actions/edit.html.erb
<% title "Edit Action" %>

<%= render 'form' %>

<p>
  <%= link_to "View", @entity_action %> |
  <%= link_to "View All", entity_actions_path %>
</p>

app/views/entity_actions/index.html.erb
<% title "Actions" %>

<div class="row">
  <div class="span8 offset2">
    <p><%= link_to "New Action", new_entity_action_path %></p>

    <%= pagination_for @entity_actions %>

    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Parent</th>
          <th>Title</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        <% for entity_action in @entity_actions %>
          <tr>
            <td><%= entity_action.parent.title if entity_action.parent %></td>
            <td><%= entity_action.title %></td>
            <td><%= truncate_html(simple_format entity_action.description) %></td>
            <%= admin_links entity_action %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= page_entries_info @entity_actions %>
    <%= pagination_for @entity_actions %>

    <p><%= link_to "New Action", new_entity_action_path %></p>
  </div>
</div>

app/views/entity_actions/new.html.erb
<% title "New Action" %>

<%= render 'form' %>

<p><%= link_to "Back to List", entity_actions_path %></p>

app/views/entity_actions/show.html.erb
<% title "Action" %>

<div class="row">
  <div class="span6 offset3">
    <p>
      <strong>Parent:</strong>
      <%= @entity_action.parent.title if @entity_action.parent %>
    </p>
    <p>
      <strong>Title:</strong>
      <%= @entity_action.title %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= simple_format @entity_action.description %>
    </p>

    <p>
      <%= link_to "Edit", edit_entity_action_path(@entity_action) %> |
      <%= link_to "Delete", @entity_action, :confirm => 'Are you sure?', :method => :delete %> |
      <%= link_to "View All", entity_actions_path %>
    </p>
  </div>
</div>