config/routes.rb
Biotriz::Application.routes.draw do
  resources :entity_actions

  resources :environment_parameters

  resources :entity_functions

  resources :entities

  resources :principles

  resources :parameters

  resources :complexities

  match 'user/edit' => 'users#edit', :as => :edit_current_user
  root :to => 'homes#index'

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users, except: :new # new users are not allowed for now

  resources :environments

  resources :sizes

end

app/models/principle.rb
# == Schema Information
#
# Table name: principles
#
#  id               :integer          not null, primary key
#  title            :string(250)      not null
#  description      :text
#  ancestry         :string(255)
#  principle_number :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Principle < ActiveRecord::Base
  attr_accessible :title, :description, :principle_number, :entities

  validates :title,
            length: { maximum: 250 },
            presence: true,
            uniqueness: true

  has_and_belongs_to_many :entities,
                          uniq: true

  self.per_page = 20
end

app/controllers/principles_controller.rb
class PrinciplesController < ApplicationController
  before_filter :login_required

  def index
    @principles = Principle.paginate page: params[:page]
  end

  def show
    @principle = Principle.find(params[:id])
  end

  def new
    @principle = Principle.new
  end

  def create
    @principle = Principle.new(params[:principle])
    if @principle.save
      redirect_to @principle, :notice => "Successfully created principle."
    else
      render :action => 'new'
    end
  end

  def edit
    @principle = Principle.find(params[:id])
  end

  def update
    @principle = Principle.find(params[:id])
    if @principle.update_attributes(params[:principle])
      redirect_to @principle, :notice  => "Successfully updated principle."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @principle = Principle.find(params[:id])
    @principle.destroy
    redirect_to principles_url, :notice => "Successfully destroyed principle."
  end
end

app/helpers/principles_helper.rb
module PrinciplesHelper
end

app/views/principles/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for @principle do |f| %>
      <%= display_error_messages_for f %>
      <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </p>
      <p>
        <%= f.label :description %>
        <%= f.text_area :description %>
      </p>
      <p>
        <%= f.label :principle_number %>
        <%= f.number_field :principle_number, min: "1" %>
      </p>
      <p><%= f.submit class: "btn btn-large btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/principles/edit.html.erb
<% title "Edit Principle" %>

<%= render 'form' %>

<p>
  <%= link_to "View", @principle %> |
  <%= link_to "View All", principles_path %>
</p>

app/views/principles/index.html.erb
<% title "Principles" %>

<div class="row">
  <div class="span8 offset2">
    <p><%= link_to "New Principle", new_principle_path %></p>

    <%= pagination_for @principles %>

    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Principle Number</th>
        </tr>
      </thead>
      <tbody>
        <% for principle in @principles %>
          <tr>
            <td><%= principle.title %></td>
            <td><%= truncate_html(simple_format principle.description) %></td>
            <td><%= principle.principle_number %></td>
            <%= admin_links principle %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= page_entries_info @principles %>
    <%= pagination_for @principles %>

    <p><%= link_to "New Principle", new_principle_path %></p>
  </div>
</div>

app/views/principles/new.html.erb
<% title "New Principle" %>

<%= render 'form' %>

<p><%= link_to "Back to List", principles_path %></p>

app/views/principles/show.html.erb
<% title "Principle" %>

<p>
  <strong>Title:</strong>
  <%= @principle.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @principle.description %>
</p>
<p>
  <strong>Principle Number:</strong>
  <%= @principle.principle_number %>
</p>

<p>
  <%= link_to "Edit", edit_principle_path(@principle) %> |
  <%= link_to "Destroy", @principle, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", principles_path %>
</p>