config/routes.rb
Biotriz::Application.routes.draw do
  resources :entity_actions

  resources :environment_parameters

  resources :entity_functions

  resources :entities

  resources :principles

  resources :parameters

  resources :complexities

  match 'user/edit' => 'users#edit', :as => :edit_current_user
  root :to => 'homes#index'

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users, except: :new # new users are not allowed for now

  resources :environments

  resources :sizes

end

app/models/entity_function.rb
# == Schema Information
#
# Table name: entity_functions
#
#  id          :integer          not null, primary key
#  title       :string(250)      not null
#  description :text
#  ancestry    :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class EntityFunction < ActiveRecord::Base
  has_ancestry

  attr_accessible :title, :description, :parent, :parent_id, :entities

  validates :title,
            presence: true,
            length: { maximum: 250 },
            uniqueness: { scope: :ancestry }

  has_and_belongs_to_many :entities,
                          join_table: "entities_ent_functions",
                          uniq: true

  self.per_page = 20
end

app/controllers/entity_functions_controller.rb
class EntityFunctionsController < ApplicationController
  before_filter :login_required

  def index
    @entity_functions = EntityFunction.paginate page: params[:page]
  end

  def show
    @entity_function = EntityFunction.find(params[:id])
  end

  def new
    @entity_function = EntityFunction.new
  end

  def create
    @entity_function = EntityFunction.new(params[:entity_function])
    if @entity_function.save
      redirect_to @entity_function, :notice => "Successfully created entity function."
    else
      render :action => 'new'
    end
  end

  def edit
    @entity_function = EntityFunction.find(params[:id])
  end

  def update
    @entity_function = EntityFunction.find(params[:id])
    if @entity_function.update_attributes(params[:entity_function])
      redirect_to @entity_function, :notice  => "Successfully updated entity function."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @entity_function = EntityFunction.find(params[:id])
    @entity_function.destroy
    redirect_to entity_functions_url, :notice => "Successfully destroyed entity function."
  end
end

app/helpers/entity_functions_helper.rb
module EntityFunctionsHelper
end

app/views/entity_functions/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for @entity_function do |f| %>
      <%= display_error_messages_for f %>
      <p>
        <%= f.label :parent_id %>
        <%= hierarchical_select :entity_function, :parent_id, EntityFunction,
            { include_blank: true }, { size: "10" } %>
      </p>
      <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </p>
      <p>
        <%= f.label :description %>
        <%= f.text_area :description %>
      </p>
      <p><%= f.submit class: "btn btn-large btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/entity_functions/edit.html.erb
<% title "Edit Entity Function" %>

<%= render 'form' %>

<p>
  <%= link_to "View", @entity_function %> |
  <%= link_to "View All", entity_functions_path %>
</p>

app/views/entity_functions/index.html.erb
<% title "Entity Functions" %>

<div class="row">
  <div class="span8 offset2">
    <p><%= link_to "New Entity Function", new_entity_function_path %></p>

    <%= pagination_for @entity_functions %>

    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Parent</th>
          <th>Title</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        <% for entity_function in @entity_functions %>
          <tr>
            <td><%= entity_function.parent.title if entity_function.parent %></td>
            <td><%= entity_function.title %></td>
            <td><%= truncate_html(simple_format entity_function.description) %></td>
            <%= admin_links entity_function %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= page_entries_info @entity_functions %>
    <%= pagination_for @entity_functions %>

    <p><%= link_to "New Entity Function", new_entity_function_path %></p>
  </div>
</div>

app/views/entity_functions/new.html.erb
<% title "New Entity Function" %>

<%= render 'form' %>

<p><%= link_to "Back to List", entity_functions_path %></p>

app/views/entity_functions/show.html.erb
<% title "Entity Function" %>

<div class="row">
  <div class="span6 offset3">
    <p>
      <strong>Parent:</strong>
      <%= @entity_function.parent.title if @entity_function.parent %>
    </p>
    <p>
      <strong>Title:</strong>
      <%= @entity_function.title %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= simple_format @entity_function.description %>
    </p>

    <p>
      <%= link_to "Edit", edit_entity_function_path(@entity_function) %> |
      <%= link_to "Delete", @entity_function, :confirm => 'Are you sure?', :method => :delete %> |
      <%= link_to "View All", entity_functions_path %>
    </p>
  </div>
</div>