config/routes.rb
Biotriz::Application.routes.draw do
  resources :entity_actions

  resources :environment_parameters

  resources :entity_functions

  resources :entities

  resources :principles

  resources :parameters

  resources :complexities

  match 'user/edit' => 'users#edit', :as => :edit_current_user
  root :to => 'homes#index'

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users, except: :new # new users are not allowed for now

  resources :environments

  resources :sizes

end

app/models/parameter.rb
# == Schema Information
#
# Table name: parameters
#
#  id          :integer          not null, primary key
#  title       :string(250)      not null
#  description :text
#  ancestry    :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Parameter < ActiveRecord::Base
  has_ancestry

  attr_accessible :title, :description, :parent, :parent_id,
                  :entities_which_improve, :entities_which_counteract

  validates :title,
            length: { maximum: 250 },
            presence: true,
            uniqueness: { scope: :ancestry }

  has_and_belongs_to_many :entities_which_improve,
                          class_name: "Entity",
                          join_table: :entities_imp_params,
                          uniq: true
  has_and_belongs_to_many :entities_which_counteract,
                          class_name: "Entity",
                          join_table: :entities_con_params,
                          uniq: true

  self.per_page = 20
end

app/controllers/parameters_controller.rb
class ParametersController < ApplicationController
  before_filter :login_required

  def index
    @parameters = Parameter.paginate page: params[:page]
  end

  def show
    @parameter = Parameter.find(params[:id])
  end

  def new
    @parameter = Parameter.new
  end

  def create
    @parameter = Parameter.new(params[:parameter])
    if @parameter.save
      redirect_to @parameter, :notice => "Successfully created parameter."
    else
      render :action => 'new'
    end
  end

  def edit
    @parameter = Parameter.find(params[:id])
  end

  def update
    @parameter = Parameter.find(params[:id])
    if @parameter.update_attributes(params[:parameter])
      redirect_to @parameter, :notice  => "Successfully updated parameter."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @parameter = Parameter.find(params[:id])
    @parameter.destroy
    redirect_to parameters_url, :notice => "Successfully destroyed parameter."
  end
end

app/helpers/parameters_helper.rb
module ParametersHelper
end

app/views/parameters/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for @parameter do |f| %>
      <%= display_error_messages_for f %>
      <p>
        <%= f.label :parent_id %>
        <%= hierarchical_select :parameter, :parent_id, Parameter,
            { include_blank: true }, { size: "10" } %>
      </p>
      <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </p>
      <p>
        <%= f.label :description %>
        <%= f.text_area :description %>
      </p>
      <p><%= f.submit class: "btn btn-large btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/parameters/edit.html.erb
<% title "Edit Parameter" %>

<%= render 'form' %>

<p>
  <%= link_to "View", @parameter %> |
  <%= link_to "View All", parameters_path %>
</p>

app/views/parameters/index.html.erb
<% title "Parameters" %>

<div class="row">
  <div class="span8 offset2">
    <p><%= link_to "New Parameter", new_parameter_path %></p>

    <%= pagination_for @parameters %>

    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Parent</th>
          <th>Title</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        <% for parameter in @parameters %>
          <tr>
            <td><%= parameter.parent.title if parameter.parent %></td>
            <td><%= parameter.title %></td>
            <td><%= truncate_html(simple_format parameter.description) %></td>
            <%= admin_links parameter %>
          </tr>
       <% end %>
      </tbody>
    </table>

    <%= page_entries_info @parameters %>
    <%= pagination_for @parameters %>

    <p><%= link_to "New Parameter", new_parameter_path %></p>
  </div>
</div>

app/views/parameters/new.html.erb
<% title "New Parameter" %>

<%= render 'form' %>

<p><%= link_to "Back to List", parameters_path %></p>

app/views/parameters/show.html.erb
<% title "Parameter" %>

<div class="row">
  <div class="span6 offset3">
    <p>
      <strong>Parent:</strong>
      <%= @parameter.parent.title if @parameter.parent %>
    </p>
    <p>
      <strong>Title:</strong>
      <%= @parameter.title %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= simple_format @parameter.description %>
    </p>

    <p>
      <%= link_to "Edit", edit_parameter_path(@parameter) %> |
      <%= link_to "Delete", @parameter, :confirm => 'Are you sure?', :method => :delete %> |
      <%= link_to "View All", parameters_path %>
    </p>
  </div>
</div>